name: Sync Files

on:
  schedule:
    - cron: "0 10 * * *"  # 北京时间凌晨 2 点触发
  workflow_dispatch:      # 允许手动触发

jobs:
  filter-and-push:
    runs-on: ubuntu-latest
    steps:
      # 检出源仓库
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          repository: DustinWin/ruleset_geodata
          ref: mihomo-ruleset
          path: source-repo

      # 筛选.list文件到临时目录
      - name: Filter .list files
        run: |
          mkdir -p filtered-files
          find source-repo -name "*.list" -exec cp --parents {} filtered-files \;
          tree filtered-files  # 调试用，查看目录结构[7](@ref)

      # 初始化目标仓库并推送
      - name: Push To Target Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TARGET_REPO_TOKEN }}
          publish_dir: ./filtered-files
          destination_dir: .  # 相对路径，推送至目标仓库根目录[8](@ref)
          publish_branch: main
          force_orphan: False  # 清空历史记录，仅保留当前文件[3](@ref)
