name: Sync Files

on:
  schedule:
    - cron: "0 10 * * *"  # 北京时间凌晨 2 点触发
  workflow_dispatch:      # 允许手动触发

jobs:
  Filter-Sync:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出源仓库（排除.git目录避免冲突）
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          repository: DustinWin/ruleset_geodata
          ref: mihomo-ruleset
          path: source-repo

      # 2. 下载额外.list文件（网页5）
      - name: Download External Files
        run: |
          mkdir -p filtered-files
          # 下载额外的规则
          wget -qO filtered-files/neteasemusic.list \
            https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.list
          wget -qO filtered-files/pikpak.list \
            https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PikPak/PikPak.list
          wget -qO filtered-files/gitlab.list \
            https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitLab/GitLab.list
          wget -qO filtered-files/bing.list \
            https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.list

      # 3. 合并本地和远程.list文件（网页6）
      - name: Merge Files
        run: |
          # 复制源仓库的.list文件到目标目录
          find source-repo -name "*.list" -exec sh -c '
            dest_path="filtered-files/${0#source-repo/}" &&
            mkdir -p "$(dirname "$dest_path")" &&
            cp -v "$0" "$dest_path"
          ' {} \;
          # 清理空目录
          find filtered-files -type d -empty -delete
          tree filtered-files

      # 3. 初始化目标仓库并增量推送
      - name: Push To Target Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SYNC_TOKEN }}  # 目标仓库的PAT密钥[2](@ref)
          publish_dir: ./filtered-files
          publish_branch: mihomo
          destination_dir: .  # 相对路径推送至根目录[6](@ref)
          force_orphan: true  # 首次推送需强制初始化分支
          disable_nojekyll: true  # 关键参数：禁止生成.nojekyll（网页7）
          allow_empty_commit: false  # 无变更时跳过提交
