name: Sync Files

on:
  schedule:
    - cron: "0 10 * * *"  # 北京时间凌晨 2 点触发
  workflow_dispatch:      # 允许手动触发

jobs:
  filter-and-sync:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出源仓库（排除.git目录避免冲突）
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          repository: DustinWin/ruleset_geodata
          ref: mihomo-ruleset
          path: source-repo
          fetch-depth: 0  # 获取完整提交历史[6](@ref)

      # 2. 筛选.list文件（排除.github目录）
      - name: Filter .list Files
        run: |
          mkdir -p filtered-files
          # 递归查找并复制.list文件，排除.github目录
          find source-repo -path 'source-repo/.github' -prune -o -name '*.list' -exec cp --parents {} filtered-files \;
          tree filtered-files  # 调试目录结构

      # 3. 初始化目标仓库并增量推送
      - name: Push To Target Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SYNC_TOKEN }}  # 目标仓库的PAT密钥[2](@ref)
          publish_dir: ./filtered-files
          destination_dir: .  # 相对路径推送至根目录[6](@ref)
          publish_branch: mihomo
          force_orphan: false  # 关闭强制覆盖，保留历史文件[7](@ref)
          allow_empty_commit: false  # 无变更时跳过提交
